# Site settings
title: Dantmcgowan | Rails, Postgres, SFDC
description: "A host of application technology services/"
url: "http://github.com/dantmcgowan"
author:
  name: "Dan McGowan"
  email: "dantmcgowan@me.com"
  url: "http://github.com/dantmcgowan"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: true
